# Site
title:              KyungRyeol (Chris)
bio:                'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.'
description:        '간단하게 설명할 수 없으면 제대로 이해하지 못하는 것이다. – 알버트 아인슈타인'
reading_time:       true
words_per_minute:   200
logo:               'https://github.com/KyungRyeol1101.png?size=200'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://kyungryeol1101.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        pygments
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   kyungryeol1101-github-io
   
# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics: UA-124565628-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              kr.yoon1101@gmail.com
#twitter:            username
facebook:           kyungryeol.yoon
github-url:         kyungryeol1101
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          kyungryeol_y
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              kryoon
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: 

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
